server:
  port: 8081
spring:
  application:
    name: PaperTrade
  datasource:
    url: 'jdbc:postgresql://localhost:5432/paper'
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha

telegram:
  alarmOnError: false
  bot:
    username: 'http://t.me/paper_trade_bot'
    token: '6570220002:AAGxwPP-vUFhG_-j206077Lmwx2B6sY2HXA'
    chatID: '-925443683'
rsa:
  publicKey: classpath:certs/public.pem
  privateKey: classpath:certs/private.pem
jwt:
  accessTokenExpiresIn: 60000000000 # ten minutes
  refreshTokenExpiresIn: 172800000 #two days

### BEGIN CORS CONFIG ###
cors:
  allowedHeaders: [ "Accept", "Accept-Language", "Origin", "Content-Language", "Content-Type", "X-Requested-With", "Authorization" ]
  allowedOrigins: [ "*" ]
  allowedMethods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD" ]
  allowCredentials: false
  exposedHeaders: [ "X-Total-Count", "Content-Disposition" ]
  urlPattern: "/**"
logging:
  level:
    org.zalando.logbook: trace
### END CORS CONFIG ###